/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5.mavenproject5;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author hp
 */

public class login extends javax.swing.JFrame {
  boolean flag=true;
  public static int account;
  public static String gmail;
  public static String userid;
  public static String pass;
    /**
     * Creates new form login
     */

   
    public login() {
        initComponents();
     addPllaceholder(juserID);
     addPllaceholder(jPassword);
     
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        signinLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        juserID = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        countinuebutton = new javax.swing.JButton();
        signupbutton = new javax.swing.JButton();
        forgetPassword2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImages(null);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(980, 567));
        setResizable(false);
        setSize(new java.awt.Dimension(980, 567));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 600));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\146b652729bf596c71cd2e1dc6ff14bf.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-40, 110, 580, 420);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\logo.jpg")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 260, 110);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 4, true));
        jPanel3.setLayout(null);

        signinLabel.setFont(new java.awt.Font("Modern No. 20", 1, 48)); // NOI18N
        signinLabel.setForeground(new java.awt.Color(102, 102, 102));
        signinLabel.setText("sign in");
        jPanel3.add(signinLabel);
        signinLabel.setBounds(20, 30, 170, 50);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(50, 130, 201, 2);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(50, 182, 210, 2);

        juserID.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        juserID.setText("User ID");
        juserID.setToolTipText("");
        juserID.setBorder(null);
        juserID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                juserIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                juserIDFocusLost(evt);
            }
        });
        juserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserIDActionPerformed(evt);
            }
        });
        jPanel3.add(juserID);
        juserID.setBounds(50, 100, 170, 30);

        jPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPassword.setText("Password");
        jPassword.setBorder(null);
        jPassword.setEchoChar('\u0000');
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(jPassword);
        jPassword.setBounds(50, 160, 150, 20);
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(180, 310, 83, 10);

        jSeparator4.setAlignmentX(0.8F);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(70, 310, 77, 15);

        jLabel6.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        jLabel6.setText("OR");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(150, 290, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Don't have account? ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(110, 320, 140, 17);

        loginbutton.setBackground(new java.awt.Color(255, 255, 255));
        loginbutton.setFont(new java.awt.Font("Palace Script MT", 1, 48)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(0, 153, 204));
        loginbutton.setText("Log in");
        loginbutton.setBorder(null);
        loginbutton.setContentAreaFilled(false);
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(loginbutton);
        loginbutton.setBounds(110, 220, 130, 50);

        countinuebutton.setBackground(new java.awt.Color(0, 102, 153));
        countinuebutton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        countinuebutton.setForeground(new java.awt.Color(255, 255, 255));
        countinuebutton.setText("Continue as a patient");
        countinuebutton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 204)));
        countinuebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countinuebuttonActionPerformed(evt);
            }
        });
        jPanel3.add(countinuebutton);
        countinuebutton.setBounds(50, 390, 250, 50);

        signupbutton.setBackground(new java.awt.Color(255, 255, 255));
        signupbutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signupbutton.setForeground(new java.awt.Color(255, 0, 0));
        signupbutton.setText("Sign up here!");
        signupbutton.setBorder(null);
        signupbutton.setBorderPainted(false);
        signupbutton.setContentAreaFilled(false);
        signupbutton.setName(""); // NOI18N
        signupbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(signupbutton);
        signupbutton.setBounds(110, 330, 129, 30);

        forgetPassword2.setBackground(new java.awt.Color(255, 255, 255));
        forgetPassword2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        forgetPassword2.setForeground(new java.awt.Color(255, 0, 0));
        forgetPassword2.setText("Forget Password?");
        forgetPassword2.setBorder(null);
        forgetPassword2.setBorderPainted(false);
        forgetPassword2.setContentAreaFilled(false);
        forgetPassword2.setName(""); // NOI18N
        forgetPassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetPassword2ActionPerformed(evt);
            }
        });
        jPanel3.add(forgetPassword2);
        forgetPassword2.setBounds(30, 180, 129, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(550, 40, 370, 470);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\corner.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(880, 430, 110, 132);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\corner2.jpg")); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(870, -20, 160, 170);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//for placeholder
    public void addPllaceholder(JTextField textfield){
        textfield.setForeground(Color.gray);
        }
      public void removePllaceholder(JTextField textfield){
        textfield.setForeground(Color.black);
    }
    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void juserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserIDActionPerformed

    private void juserIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juserIDFocusGained
       if(juserID.getText().equals("User ID")){
           juserID.setText(null);
           juserID.requestFocus();
          removePllaceholder(juserID); 
       }
       
    }//GEN-LAST:event_juserIDFocusGained

    private void juserIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juserIDFocusLost
       if(juserID.getText().equals("")){
           addPllaceholder(juserID);
           juserID.setText("User ID");
       }
    }//GEN-LAST:event_juserIDFocusLost

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
          if(jPassword.getText().equals("Password")){
           jPassword.setText(null);
           jPassword.requestFocus();
           jPassword.setEchoChar('*');
          removePllaceholder(jPassword); 
       }
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
            if(jPassword.getText().equals("")){
           addPllaceholder(jPassword);
           jPassword.setText("Password");
       }
    }//GEN-LAST:event_jPasswordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void signupbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbuttonActionPerformed
     
        signUpframe sign=new signUpframe();
        sign.setLocationRelativeTo(null);
        sign.setVisible(true);
    }//GEN-LAST:event_signupbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
          
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String strurl="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(strurl,"c##project","20212022");
            Statement stmt=con.createStatement();
            userid=juserID.getText();
            pass=jPassword.getText();
            if((userid.equals("User ID"))||(pass.equals("Password"))){
              jSeparator1.setBorder(new LineBorder (Color.red,1));
              jSeparator2.setBorder(new LineBorder (Color.red,1)); 
            }
            else {
            int s1=0;
            ResultSet rs=stmt.executeQuery("select ACCOUNT_ID from MANAGER where SSN ="+userid+"");
            if(rs.next()){
             s1=rs.getInt(1);if(s1==0){jSeparator1.setBorder(new LineBorder (Color.red,1)); jSeparator2.setBorder(new LineBorder (Color.red,1));}else {jSeparator1.setBorder(new LineBorder (Color.gray,1));flag=true;}}
            else flag=false;
            if(flag==true){
             ResultSet rs2=stmt.executeQuery("select ACCOUNT_PASSWORD from USER_ACCOUNT where ACCOUNT_ID="+s1+"");
             if(rs2.next()){
             String s2=rs2.getString(1);
             if(s2.equals(pass)){
                dispose();
                 manager_design manger=new manager_design();
                 manger.setLocationRelativeTo(null);
                 manger.setVisible(true);}
             else {
                   jSeparator2.setBorder(new LineBorder (Color.red,1));}  
                 
           }
            }
            else{
                flag=true;
             int s3=0;
            ResultSet rs3=stmt.executeQuery("select ACCOUNT_ID from EMPLOYEE where SSN ="+userid+"");
            if(rs3.next()){
             s1=rs3.getInt(1);if(s1==0){jSeparator1.setBorder(new LineBorder (Color.red,1)); jSeparator2.setBorder(new LineBorder (Color.red,1));}else jSeparator1.setBorder(new LineBorder (Color.gray,1));}
            else {flag=false;}
            if(flag==true){
             ResultSet rs4=stmt.executeQuery("select ACCOUNT_PASSWORD from USER_ACCOUNT where ACCOUNT_ID="+s1+"");
             if(rs4.next()){
             String s2=rs4.getString(1);
             if(s2.equals(pass)){
                dispose();
                 employee_design employee=new employee_design();
                 employee.setLocationRelativeTo(null);
                 employee.setVisible(true);}
             else {
                   jSeparator2.setBorder(new LineBorder (Color.red,1)); }  
                 
               }}
            else{jSeparator1.setBorder(new LineBorder (Color.red,1)); jSeparator2.setBorder(new LineBorder (Color.red,1)); }
                    }   
            }        
        } catch (Exception ex) {
               JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void forgetPassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetPassword2ActionPerformed
        Forget forget=new Forget();
        forget.setLocationRelativeTo(null);
        forget.setVisible(true);
    }//GEN-LAST:event_forgetPassword2ActionPerformed

    private void countinuebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countinuebuttonActionPerformed
       //jPanel1.setVisible(false);
       this.setVisible(false);
        patient pa=new patient();
        pa.setVisible(true);
         pa.setBounds(0, 0, 980, 580);
        pa.setLocationRelativeTo(null);
      
    }//GEN-LAST:event_countinuebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countinuebutton;
    private javax.swing.JButton forgetPassword2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField juserID;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel signinLabel;
    private javax.swing.JButton signupbutton;
    // End of variables declaration//GEN-END:variables

       
}
