/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5.mavenproject5;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import oracle.jdbc.pool.OracleDataSource;
import static project5.mavenproject5.patientID.pid;


/**
 *
 * @author hp
 */
public class testrecord extends javax.swing.JFrame {

    /**
     * Creates new form testrecord
     */
    public testrecord() {
        initComponents();
         addPllaceholder(jTextField1);
           try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String strurl="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(strurl,"c##project","20212022");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from EXAMINATION_RECORD,EXAMINATION where EXAMINATION_RECORD.SSN ="+patientID.pid+"and EXAMINATION_RECORD.EXAMINATION_NAME=EXAMINATION.EXAMINATION_NAME");
            
            while(rs.next()){
                if(patientID.psex=='M'){
                Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_MALE")};
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
                else{Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_FEMALE")};
                DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
            }
            
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\record.jpg")); // NOI18N
        jLabel1.setText("Medical tests record");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 620, 70);

        jScrollPane1.setBackground(new java.awt.Color(0, 204, 204));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "test name", " Date", "Result Value", "Normal Range"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAlignmentX(0.0F);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 180, 880, 270);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Search by name", "search by date" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(600, 130, 140, 28);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(750, 130, 170, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\close.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(930, 20, 21, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\databasepicture\\search-icon.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(920, 130, 30, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 153));
        jButton3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("view whole recod");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(50, 130, 200, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void addPllaceholder(JTextField textfield){
        textfield.setForeground(Color.gray);
        }
      public void removePllaceholder(JTextField textfield){
        textfield.setForeground(Color.black);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
       patient pa=new patient();
        pa.setVisible(true);
         pa.setBounds(0, 0, 980, 580);
        pa.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String txt=jTextField1.getText();
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
       try{
        DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String strurl="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(strurl,"c##project","20212022");
            Statement stmt=con.createStatement();
        if(txt.isEmpty()){jTextField1.setBorder(new LineBorder (Color.red,1));}
        else if(jComboBox1.getSelectedIndex()==0){
               model.setRowCount(0);
               ResultSet rs=stmt.executeQuery("select * from EXAMINATION_RECORD,EXAMINATION where EXAMINATION_RECORD.SSN ='"+patientID.pid+"'and (UPPER (EXAMINATION_RECORD.EXAMINATION_NAME) like UPPER('%"+txt+"%')or LOWER (EXAMINATION_RECORD.EXAMINATION_NAME) like LOWER('%"+txt+"%'))and EXAMINATION_RECORD.EXAMINATION_NAME=EXAMINATION.EXAMINATION_NAME");
                model.setRowCount(0);
               while(rs.next()){
                if(patientID.psex=='M'){
                Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_MALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
                else{Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_FEMALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
            }  
        }
        else{
         try{
             SimpleDateFormat date=new SimpleDateFormat("yyyy-MM-dd");
             date.parse(txt);
              }catch(Exception e){
           JOptionPane.showMessageDialog(null, "wrong date format"); return; 
         }
              ResultSet rs=stmt.executeQuery("select * from EXAMINATION_RECORD,EXAMINATION where EXAMINATION_RECORD.SSN ='"+patientID.pid+"'and EXAMINATION_RECORD_DATE ={d'"+txt+"'}and EXAMINATION_RECORD.EXAMINATION_NAME=EXAMINATION.EXAMINATION_NAME");
                model.setRowCount(0);
               while(rs.next()){
                 if(patientID.psex=='M'){
                Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_MALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
                else{Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_FEMALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
               }
        }
       } catch (Exception ex) {
          //  JOptionPane.showMessageDialog(null,"invalid date");
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String strurl="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con=DriverManager.getConnection(strurl,"c##project","20212022");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from EXAMINATION_RECORD,EXAMINATION where EXAMINATION_RECORD.SSN ="+patientID.pid+"and EXAMINATION_RECORD.EXAMINATION_NAME=EXAMINATION.EXAMINATION_NAME");
            
            while(rs.next()){
                if(patientID.psex=='M'){
                Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_MALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
                else{Object[]row={rs.getString("EXAMINATION_NAME"),rs.getDate("EXAMINATION_RECORD_DATE"),rs.getFloat("RESULT_VALUE"),rs.getString("NORMAL_RANGE_FOR_FEMALE")};
                model=(DefaultTableModel)jTable1.getModel();
                model.addRow(row);}
            }
            
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
 if(jTextField1.getText().equals("yyyy-MM-dd")&&(jComboBox1.getSelectedIndex()==1)){
           jTextField1.setText(null);
           jTextField1.requestFocus();
          removePllaceholder(jTextField1); 
    }//GEN-LAST:event_jTextField1FocusGained
    }
    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
            if(jTextField1.getText().equals("")&&(jComboBox1.getSelectedIndex()==1)){
           addPllaceholder(jTextField1);
           jTextField1.setText("yyyy-MM-dd");
            }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if(jComboBox1.getSelectedIndex()==1)
       {addPllaceholder(jTextField1);
           jTextField1.setText("yyyy-MM-dd");}
       else{jTextField1.setText(null);}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testrecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testrecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
